#pragma once

#include "Animal.h"
#include "Chicken.h"
#include "Cow.h"
#include "Pig.h"
#include "Sheep.h"
#include "Squid.h"
#include "WaterAnimal.h"
#include "Wolf.h"
#include "Golem.h"
#include "MushroomCow.h"
#include "SnowMan.h"
#include "Ocelot.h"
#include "VillagerGolem.h"
#include "EntityHorse.h"
#include "Fox.h"
